#include "services/storage.h"
#include "diskio.h"
#include <string.h>

volatile FRESULT storage_mount_status = FR_NOT_READY;
volatile DWORD storage_sector_count = 0U;
volatile WORD storage_sector_size = 0U;
volatile uint8_t storage_format_request = 0U;
volatile FRESULT storage_format_status = FR_NOT_READY;
volatile uint8_t storage_test_request = 0U;
volatile FRESULT storage_test_status = FR_NOT_READY;
volatile UINT storage_test_bytes_written = 0U;
volatile UINT storage_test_bytes_read = 0U;

/* FatFs 格式化的工作缓冲区，不占用任务栈。 */
static uint8_t storage_mkfs_work[4096];
static const uint8_t storage_test_write_data[64] =
{
  0x53U, 0x44U, 0x20U, 0x63U, 0x61U, 0x6DU, 0x65U, 0x72U,
  0x61U, 0x20U, 0x73U, 0x74U, 0x6FU, 0x72U, 0x61U, 0x67U,
  0x65U, 0x20U, 0x73U, 0x65U, 0x6CU, 0x66U, 0x2DU, 0x74U,
  0x65U, 0x73U, 0x74U, 0x20U, 0x70U, 0x61U, 0x73U, 0x73U,
  0x00U, 0x11U, 0x22U, 0x33U, 0x44U, 0x55U, 0x66U, 0x77U,
  0x88U, 0x99U, 0xAAU, 0xBBU, 0xCCU, 0xDDU, 0xEEU, 0xFFU,
  0x5AU, 0xA5U, 0x3CU, 0xC3U, 0x69U, 0x96U, 0xF0U, 0x0FU,
  0x12U, 0x34U, 0x56U, 0x78U, 0x9AU, 0xBCU, 0xDEU, 0xF1U
};
static uint8_t storage_test_read_data[sizeof(storage_test_write_data)];
/* QVGA 一行 BMP BGR 像素最多 320 * 3 = 960 字节。 */
static uint8_t storage_bmp_row[960];

static void Storage_WriteU16LE(uint8_t *target, uint16_t value)
{
  target[0] = (uint8_t)value;
  target[1] = (uint8_t)(value >> 8);
}

static void Storage_WriteU32LE(uint8_t *target, uint32_t value)
{
  target[0] = (uint8_t)value;
  target[1] = (uint8_t)(value >> 8);
  target[2] = (uint8_t)(value >> 16);
  target[3] = (uint8_t)(value >> 24);
}

FRESULT Storage_Mount(void)
{
  storage_sector_count = 0U;
  storage_sector_size = 0U;

  /* USERPath is generated by FATFS_LinkDriver(), normally "0:". */
  storage_mount_status = f_mount(&USERFatFS, (const TCHAR *)USERPath, 1U);
  if (storage_mount_status != FR_OK)
  {
    return storage_mount_status;
  }

  if (disk_ioctl(0U, GET_SECTOR_COUNT, (void *)&storage_sector_count) != RES_OK)
  {
    storage_mount_status = FR_DISK_ERR;
    return storage_mount_status;
  }

  if (disk_ioctl(0U, GET_SECTOR_SIZE, (void *)&storage_sector_size) != RES_OK)
  {
    storage_mount_status = FR_DISK_ERR;
  }

  return storage_mount_status;
}

FRESULT Storage_SaveRGB565BMP(const uint8_t *rgb565_be, uint16_t width,
                               uint16_t height, const TCHAR *path)
{
  uint8_t header[54] = {0};
  uint32_t image_size;
  uint32_t file_size;
  uint32_t source_offset;
  uint16_t source_y;
  uint16_t x;
  UINT bytes_written;
  FRESULT result;

  if ((rgb565_be == NULL) || (path == NULL) || (width == 0U) || (height == 0U) ||
      ((uint32_t)width * 3U > sizeof(storage_bmp_row)))
  {
    return FR_INVALID_PARAMETER;
  }

  if (storage_mount_status != FR_OK)
  {
    result = Storage_Mount();
    if (result != FR_OK)
    {
      return result;
    }
  }

  image_size = (uint32_t)width * (uint32_t)height * 3U;
  file_size = 54U + image_size;
  header[0] = 'B';
  header[1] = 'M';
  Storage_WriteU32LE(&header[2], file_size);
  Storage_WriteU32LE(&header[10], 54U);
  Storage_WriteU32LE(&header[14], 40U);
  Storage_WriteU32LE(&header[18], width);
  Storage_WriteU32LE(&header[22], height);
  Storage_WriteU16LE(&header[26], 1U);
  Storage_WriteU16LE(&header[28], 24U);
  Storage_WriteU32LE(&header[34], image_size);

  result = f_open(&USERFile, path, FA_CREATE_ALWAYS | FA_WRITE);
  if (result != FR_OK)
  {
    return result;
  }

  result = f_write(&USERFile, header, sizeof(header), &bytes_written);
  if ((result != FR_OK) || (bytes_written != sizeof(header)))
  {
    (void)f_close(&USERFile);
    return (result == FR_OK) ? FR_DISK_ERR : result;
  }

  /* BMP 从底行开始存储；RGB565 输入是 OV5640/DCMI 的高字节在前。 */
  for (source_y = height; source_y > 0U; source_y--)
  {
    source_offset = ((uint32_t)(source_y - 1U) * width) * 2U;
    for (x = 0U; x < width; x++)
    {
      uint8_t high = rgb565_be[source_offset + ((uint32_t)x * 2U)];
      uint8_t low = rgb565_be[source_offset + ((uint32_t)x * 2U) + 1U];
      uint8_t red5 = high >> 3;
      uint8_t green6 = (uint8_t)(((high & 0x07U) << 3) | (low >> 5));
      uint8_t blue5 = low & 0x1FU;

      storage_bmp_row[(uint32_t)x * 3U] = (uint8_t)((blue5 << 3) | (blue5 >> 2));
      storage_bmp_row[((uint32_t)x * 3U) + 1U] = (uint8_t)((green6 << 2) | (green6 >> 4));
      storage_bmp_row[((uint32_t)x * 3U) + 2U] = (uint8_t)((red5 << 3) | (red5 >> 2));
    }

    result = f_write(&USERFile, storage_bmp_row, (UINT)((uint32_t)width * 3U),
                     &bytes_written);
    if ((result != FR_OK) || (bytes_written != (UINT)((uint32_t)width * 3U)))
    {
      (void)f_close(&USERFile);
      return (result == FR_OK) ? FR_DISK_ERR : result;
    }
  }

  result = f_close(&USERFile);
  return result;
}

FRESULT Storage_SaveRawImage(const uint8_t *data, uint32_t length,
                              const TCHAR *directory, const TCHAR *path)
{
  const uint32_t write_block_size = 16000U;  /* 与原 F429 拍照任务一致。 */
  uint32_t offset = 0U;
  uint32_t chunk_size;
  UINT bytes_written;
  FRESULT result;

  if ((data == NULL) || (length == 0U) || (directory == NULL) || (path == NULL))
  {
    return FR_INVALID_PARAMETER;
  }

  if (storage_mount_status != FR_OK)
  {
    result = Storage_Mount();
    if (result != FR_OK)
    {
      return result;
    }
  }

  result = f_mkdir(directory);
  if ((result != FR_OK) && (result != FR_EXIST))
  {
    return result;
  }

  result = f_open(&USERFile, path, FA_WRITE | FA_CREATE_ALWAYS);
  if (result != FR_OK)
  {
    return result;
  }

  while (offset < length)
  {
    chunk_size = length - offset;
    if (chunk_size > write_block_size)
    {
      chunk_size = write_block_size;
    }

    result = f_write(&USERFile, &data[offset], (UINT)chunk_size, &bytes_written);
    if ((result != FR_OK) || (bytes_written != (UINT)chunk_size))
    {
      (void)f_close(&USERFile);
      return (result == FR_OK) ? FR_DISK_ERR : result;
    }
    offset += chunk_size;
  }

  result = f_sync(&USERFile);
  if (f_close(&USERFile) != FR_OK)
  {
    return FR_DISK_ERR;
  }
  return result;
}

void Storage_Process(void)
{
  if (storage_format_request != 1U)
  {
    /* 格式化未请求时，才允许执行普通读写自检。 */
  }
  else
  {
    /* 先改为 2，再执行耗时操作；避免本次运行重复格式化。 */
    storage_format_request = 2U;
    storage_format_status = f_mkfs((const TCHAR *)USERPath, FM_FAT32, 0U,
                                   storage_mkfs_work, sizeof(storage_mkfs_work));

    if (storage_format_status == FR_OK)
    {
      storage_mount_status = Storage_Mount();
    }
    return;
  }

  if (storage_test_request != 1U)
  {
    return;
  }

  storage_test_request = 2U;
  storage_test_bytes_written = 0U;
  storage_test_bytes_read = 0U;
  storage_test_status = FR_NOT_READY;

  if (storage_mount_status != FR_OK)
  {
    storage_test_status = Storage_Mount();
    if (storage_test_status != FR_OK)
    {
      return;
    }
  }

  storage_test_status = f_open(&USERFile, "0:/SDTEST.BIN", FA_CREATE_ALWAYS | FA_WRITE);
  if (storage_test_status == FR_OK)
  {
    storage_test_status = f_write(&USERFile, storage_test_write_data,
                                  sizeof(storage_test_write_data),
                                  (UINT *)&storage_test_bytes_written);
  }
  if ((storage_test_status == FR_OK) &&
      (storage_test_bytes_written != sizeof(storage_test_write_data)))
  {
    storage_test_status = FR_DISK_ERR;
  }
  if (f_close(&USERFile) != FR_OK)
  {
    storage_test_status = FR_DISK_ERR;
  }

  if (storage_test_status == FR_OK)
  {
    storage_test_status = f_open(&USERFile, "0:/SDTEST.BIN", FA_READ);
  }
  if (storage_test_status == FR_OK)
  {
    storage_test_status = f_read(&USERFile, storage_test_read_data,
                                 sizeof(storage_test_read_data),
                                 (UINT *)&storage_test_bytes_read);
  }
  if ((storage_test_status == FR_OK) &&
      ((storage_test_bytes_read != sizeof(storage_test_read_data)) ||
       (memcmp(storage_test_write_data, storage_test_read_data,
               sizeof(storage_test_write_data)) != 0)))
  {
    storage_test_status = FR_DISK_ERR;
  }
  if (f_close(&USERFile) != FR_OK)
  {
    storage_test_status = FR_DISK_ERR;
  }

  /* 无论校验是否成功，都删除这一个临时测试文件。 */
  if (f_unlink("0:/SDTEST.BIN") != FR_OK)
  {
    storage_test_status = FR_DISK_ERR;
  }
}
